# Generated by Django 5.2.5 on 2025-08-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_internship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='internship',
            name='role',
            field=models.CharField(max_length=255),
        ),
    ]
