# Generated by Django 5.2.5 on 2025-08-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_internship_company_alter_internship_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='Contact',
        ),
    ]
